server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mystore
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false
    mode: LEGACYHTML5



